export const enum Colors {
  'Dynamic' = 'dynamic',
  'Primary' = 'primary',
  'Secondary' = 'secondary',
  'Tertiary' = 'tertiary',
  'Success' = 'success',
  'Danger' = 'danger',
  'Warning' = 'warning',
  'Light' = 'light',
  'Medium' = 'medium',
  'Dark' = 'dark',
  'GradientDynamic' = 'gradient-dynamic',
  'GradientPrimary' = 'gradient-primary',
  'GradientSecondary' = 'gradient-secondary',
  'GradientTertiary' = 'gradient-tertiary',
  'GradientSuccess' = 'gradient-success',
  'GradientDanger' = 'gradient-danger',
  'GradientWarning' = 'gradient-warning',
  'GradientLight' = 'gradient-light',
  'GradientMedium' = 'gradient-medium',
  'GradientDark' = 'gradient-dark',
}

export const enum Sizes {
  'XXXS' = 'xxxs',
  'XXS' = 'xxs',
  'XS' = 'xs',
  'SS' = 'ss',
  'SM' = 'sm',
  'MD' = 'md',
  'ML' = 'ml',
  'LG' = 'lg',
  'SL' = 'sl',
  'XL' = 'xl',
  'XXL' = 'xxl',
  'XXXL' = 'xxxl',
}
